### ISSUE TITLE
several questions

### ISSUE THREAD

**Issue by ghost** [git-deploy/git-deploy#37]
Hello,
can someone help to configure git-deploy?
1. git-deploy must be installed on laptop and on server?
2. git-deploy installation - copying git-deploy file to (for example) /usr/bin?
3. all repos configs are in it-deploy.conf or there are possibility to store configs in repos?
4. git repo must include deploy directory?

**Comment by avar** [comment]
Sure, no problem:
1. You _can_ run it from your laptop, but the way we run it is that we run it from a "staging" server, i.e. one server that everyone who deploys logs into and does the deployment from that role. A large part of git-deploy is managing the locking mechanism where only one deployment can be underway at a time, having everyone running it from their laptop wouldn't give you that
2. We just clone git-deploy.git and have a symlink to bin/git-deploy. So a symlink to that in /usr/bin will work
3. Our config is read from git-config, so you can do whatever works with git configuration. We store the config for all repos in one global file, but you can also have that per-repo stuff in the repository itself if you'd like. Both will work, git-config merges all the config file it loads into one thing before spitting out the result.
4. Yes.

**Comment by guest20** [comment]
> git-deploy must be installed on laptop and on server?

git-deploy needs to be on the machine you'll test your code on.
your sync hook just copies the git directory (except `.git`) to the other boxes

> git-deploy installation - copying git-deploy file to (for example) /usr/bin?

You just have to put bin/git-deploy in your $PATH, you can link from `/usr/bin` if you like.

> all repos configs are in it-deploy.conf or there are possibility to store configs in repos?

You can set attributes on the repo to configure how git-deploy works, yes.
You can also set the path to `git-deploy.conf` in the global git config for a box eg 

```
$ cat /etc/gitconfig
[deploy]
        config-file = /etc/git-deploy.conf
```

> git repo must include deploy directory?

No, a file called {{.deploy}} will be dropped into the directory to tell your sync software which version the repo was set to when {{sync}} was called, that way you don't have to copy your {{.git}} directory to the production machines.

**Comment by avar** [comment]
FWIW I understood question 4 to be "Does the directory I'm deploying from need to be a git checkout". But if you're talking about the `.deploy` file we make see @guest20's answer.

**Comment by guest20** [comment]
If you have more than one user, you have to share the git-repo in order for git-deploy's on-disk locking to work. If y'all each do it from your own laptop, there won't be any locking.

If you're just using it for keeping track of your own code, this doesn't matter as much (or at all, really).

**Comment by ghost** [comment]
Thank you very much for answers, it's very interesting and helpful for me.

Now I a, studying to work with git-deploy, so, my laptop is "staging server", and a VPS a "production server". After I will work with teammates with our servers - now I want to know how to use git-deploy for locking and rollout history saving.

On laptop and server I place git-deploy in home directory and add it to PATH and execute  `exec $SHELL`

I think understand first 3 items, thanks.

So, I create git repo on laptop

```
git init staging
```

and on production

```
git init production
```

In staging repo I create `gitconfig` file with content

```
[deploy]
            config-file = .git-deploy.conf
```

and add file .git-deploy.conf

```
;; Global options
    [deploy]
            ;; If this file exists all rollouts are blocked
            block-file = /etc/ROLLOUTS_BLOCKED

            ;; What strategy should we use to detect the repo name?
            repo-name-detection = dot-git-parent-dir

            ;; Where to store the timing information
            log-directory = /var/log/deploy

            ;; We want timing information
            log-timing-data = true
```

Now I should write git-deploy hooks?

**Comment by guest20** [comment]
You need a script named `${tag-prefix}.sync` in `${hook-dir}/sync/`. That script should copy your code to your production machines via rsync / ftp / carrier pigeon, to a directory named after the `tag:` entry in `.deploy`.

once the new version of the code is copied there, you want to tell your webserver to reload your application (if it doesn't auto-reload)

**Comment by ghost** [comment]
```
# INFO : git pull --no-rebase origin
# FATAL: failed to git pull --no-rebase from 'origin' errorcode: 1
```

What can cause this error?

**Comment by avar** [comment]
Run it in the shell and you'll see the full output from Git.

**Comment by ghost** [comment]
lock implemented on git user level, right?

**Comment by avar** [comment]
No. On a checkout level, and you should have one checkout per deployment.
That guarantees that you don't have conflicting deployments.

**Comment by ghost** [comment]
I will try do it again.

1) I create private repo on gitlab - `git-deploy-test` - and clone it to certain directory on laptop.
2) On VPS I install `git-deploy` and create bare git repo 
3) On laptop in `git-deploy-test` repo:

```
git remote add production a93ushakov@a93ushakov.koding.io:/home/a93ushakov/production/
```

4) on laptop I had created new file, added it to git control and executed

```
git push -u production master
git config --add deploy.tag-prefix ROLLOUT
git config --add deploy.deploy-file .deploy
```

5) As I understand, `git-deploy` provide to abilities: lock and make rollout manually (git deploy release), or lock and use hook for copying.
For beginning I try to execute `git deploy release`, but it give the error `# FATAL: You aren't allowed to use the 'release' action for the prefix 'ROLLOUT'`.

How to avoid this error, where I was wrong?
